ROUTINE Test1
 //comment1
 ;comment2
#;comment3
Begin() [] Public
{
    /* some
    multiline
    comment*/
    Write "The begining",! ;writing some text
    Do next
    Do Begin^Test2("Test1")
}

next(testPar)[O]
{
    Write "Next Line",!
}

Funcky() { Write "Oneliner" }

Oneliner(TestPar)  Write "old-school oneliner"
Oneliner2   Write "old-school oneliner"

Dots
    If 1 Do
    .Write "with dot notation"
    Quit

NestedLabels
    Write "some old school functionality: nested labels",!
Nested
    Write "this line is in a nested label"
    Quit