version: "2.2"
services:
  iris:
    container_name: jewa
    init: true
    image: store/intersystems/iris-community:2020.3.0.221.0
     # If your CPU has >8 cores limit InterSystems IRIS CE to 8 with
    cpuset: "0-3"
    volumes:
      - data:/durable
      - ./shared:/shared
      - ./iris/src:/src
    environment:
     - ISC_DATA_DIRECTORY=/durable
    ports:
     - 9100:52773
     - 9101:1972
    #command: --password-file /durable/password/password.txt
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ./files/
      o: bind